baseURL = "https://tillery.fyi/"
languageCode = "en-US"
title = "Tillery"
# Enable Google Analytics by entering your tracking code
#googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.jpg"
  author = "Tillery"
  description = "Hi. I'm Tillery"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "AreTillery"
  Email         = "tillery@tillery.fyi"
  Twitter       = "AreTillery"
  LinkedIn      = "AreTillery"

[markup.goldmark.renderer]
unsafe= true

## Main Menu
#[[menu.main]]
#  name = "blog"
#  weight = 100
#  identifier = "blog"
#  url = "/blog/"
#[[menu.main]]
#  name = "projects"
#  identifier = "projects"
#  weight = 200
#  url = "/projects/"
[[menu.main]]
  name = "pgp"
  identifier = "pgp"
  url = "/pgp/"
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "about"
#[[menu.main]]
#  name = "resume"
#  identifier = "resume"
#  weight = 300
#  url = "/resume/"
